### ISSUE TITLE
Migrate to Maven, and get JSkills into a public Maven repository

### ISSUE THREAD

**Issue by sanity** [nsp/JSkills#4]
Here is some advice on hosting Maven repositories, including how to do it with Github: http://cemerick.com/2010/08/24/hosting-maven-repos-on-github/

Note that this will require using only libraries that are themselves in a maven repository.  You can search for such libraries here: http://mvnrepository.com/

**Comment by nikku** [comment]
@nsp Are you interested in getting this into maven central? I could look into the issue and perform the required changes.

**Comment by nsp** [comment]
I think that's a great idea. I haven't been involved in the Java environment or community for quite some time, so I'll just follow your recommendations. Or if you want to upload your fork, I have no problem it eclipsing this repo.

**Comment by Nyeng** [comment]
Any update on this? :+1: for the idea

**Comment by nsp** [comment]
I believe that one or more forks have been made mvn-compatible, and it's just a matter of uploading them. Unfortunately, I simply do not have the time to follow up, so I recommend talking to one of the fork owners about uploading theirs.

**Comment by MiniDigger** [comment]
since its not navenized, any chance you could get it into maven central?

**Comment by Nyeng** [comment]
looks like the build is failing? https://travis-ci.org/nsp/JSkills/branches

**Comment by nsp** [comment]
I don't have the time to maintain this repository, but I'm happy designate a new primary repository for JSkills. Any interest in taking over, @Nyeng, @micheljung, @pmg1991, @MiniDigger, @nikku, @sanity, @gesundkrank, @mzuber?

What I'd do is create a new commit that deletes all the code and replaces the README with a link to your fork, and you'll get all the credit (and responsibility) going forwards.

**Comment by pmg1991** [comment]
@nsp i'm up. If anybody else doesn't.

**Comment by gesundkrank** [comment]
@nsp I would also be up for doing it. 

And I already released a public version of my fork some time ago (I needed it in another repo). 
Sorry for not mentioning it here. :smirk:

http://mvnrepository.com/artifact/de.gesundkrank.jskills/jskills

**Comment by pmg1991** [comment]
Anybody have any improvement plan for the JSkills like performance, code coverage, test cases, please let me know?

**Comment by nsp** [comment]
Danke, @gesundkrank, you win the prize! I hope and trust that you will be a better steward of this project than I have been.

**Comment by gesundkrank** [comment]
Wow. Thanks a lot! I'll give my best. 🙇
